name: My Workflow
on: push

jobs:
  test:
    name: Integration Tests
    runs-on: ubuntu-latest
    steps:
    - name: checkout code
      uses: actions/checkout@v2
    - name: figure out dir
      run: ls -al
    - name: run tests
      run: ./test.sh
    - name: run docker
      run: docker run alpine:latest ls
    - name: write some content
      run: mkdir public && echo "<h1>hello world</h1>" > ./public/index.html
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./public
